name: build test

on:
  workflow_dispatch:

jobs:

  build-cuda-ubuntu-docker:
    name: build in ubuntu docker with cuda
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:11.4.2-devel-ubuntu20.04

      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:11.4.2-devel-ubuntu20.04

      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-ubuntu -f cuda-ubuntu.dockerfile .

      - name: copy build
        run: |
          docker run -it --rm  -v ${{ github.workspace }}/artifact:/app/workspace ffmpeg:cuda-ubuntu bash copy.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-dynamic-build
          path: ${{ github.workspace }}/artifact/**/*


  build-full-static:
    if: ${{ false }}
    name: full static build in docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:11.4.2-devel-ubuntu20.04
      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:11.4.2-devel-ubuntu20.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-static -f full-static.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-static -buildconf
